radixdlt/scrypto-challenges

1-exchanges/croq_order_book/Cargo.toml, 1-exchanges/croq_order_book/README.md, 1-exchanges/croq_order_book/src/lib.rs, 1-exchanges/croq_order_book/tests/lib.rs, LICENSE
have a look at the readme for a good description
=> Traditional order book

1-exchanges/marketplace/Cargo.toml, 1-exchanges/marketplace/README.md, 1-exchanges/marketplace/src/data.rs, 1-exchanges/marketplace/src/lib.rs, 1-exchanges/marketplace/tests/demo.ps1, 1-exchanges/marketplace/tests/demo.sh, 1-exchanges/marketplace/tests/steps.ps1
Updated my marketplace example to Scrypto v0.3. Admittedly I didn't manage to rework the orders properly. So for now they are simply not cleaned up once settled because Vaults are not allowed to be removed anymore.
This has to be changed so that shared vaults are used and the orders only contain the amounts they hold in those shared vaults.
I've started [feature branch](https://github.com/machisuji/scrypto-challenges/tree/feature/shared-vaults) for that but I won't manage to complete until the end of the day. So here we are.
=> updated marketplace to scrypto v0.3

smaller-challenges/token2poche/Cargo.toml, smaller-challenges/token2poche/src/lib.rs, smaller-challenges/token2poche/tests/lib.rs
=> Team Token2Poche (ent)

smaller-challenges/budenz/Cargo.toml, smaller-challenges/budenz/src/lib.rs, smaller-challenges/budenz/tests/lib.rs, smaller-challenges/budenz/tx.rtm
Our ID-s:
#4126755519
#4126789539
#4088590949
#4099649499
=> team Budenz

smaller-challenges/scryptonians/Cargo.toml, smaller-challenges/scryptonians/src/lib.rs, smaller-challenges/scryptonians/src/tx.rtm, smaller-challenges/scryptonians/tests/lib.rs
=> scryptonians

smaller-challenges/Tricoin/Cargo.toml, smaller-challenges/Tricoin/src/lib.rs, smaller-challenges/Tricoin/tests/lib.rs
=> Create scrypto team challenge fork - Tricoin

smaller-challenges/babylonians/Cargo.toml, smaller-challenges/babylonians/src/lib.rs, smaller-challenges/babylonians/tests/lib.rs
=> thank you for the event :-)

smaller-challenges/first-row-muc-ftw/.idea/.gitignore, smaller-challenges/first-row-muc-ftw/.idea/first-row-muc-ftw.iml, smaller-challenges/first-row-muc-ftw/.idea/modules.xml, smaller-challenges/first-row-muc-ftw/.idea/vcs.xml, smaller-challenges/first-row-muc-ftw/Cargo.toml, smaller-challenges/first-row-muc-ftw/src/lib.rs, smaller-challenges/first-row-muc-ftw/tests/lib.rs
=> first_row_muc_ftw Submission

smaller-challenges/based_in_lisbon/Cargo.toml, smaller-challenges/based_in_lisbon/src/lib.rs, smaller-challenges/based_in_lisbon/src/vars.sh, smaller-challenges/based_in_lisbon/tests/lib.rs
=> Challenge completed

smaller-challenges/we-got-a-lambo/Cargo.toml, smaller-challenges/we-got-a-lambo/src/lib.rs, smaller-challenges/we-got-a-lambo/tests/lib.rs
Code challenge Lisbon 23/07/2022
team-member-1-ticket-number", "4103326979"
team-member-2-ticket-number", "4023945879"
team-member-3-ticket-number", "4055329479"
team-member-4-ticket-number", "4102635929"
team-member-5-ticket-number", "4024480349"
=> we-got-a-lambo code challenge

smaller-challenges/fuck-you-money/Cargo.toml, smaller-challenges/fuck-you-money/src/lib.rs, smaller-challenges/fuck-you-money/tests/lib.rs
Submission from the team Fuck you Money !
=> Radix Workshop

smaller-challenges/ForintInu/Cargo.toml, smaller-challenges/ForintInu/src/lib.rs, smaller-challenges/ForintInu/tests/lib.rs
=> ForintInu for the win

smaller-challenges/suleiman-token-sale/Cargo.toml, smaller-challenges/suleiman-token-sale/src/lib.rs, smaller-challenges/suleiman-token-sale/tests/lib.rs
=> Our token sale

smaller-challenges/egonomics/Cargo.toml, smaller-challenges/egonomics/change_price.rtm, smaller-challenges/egonomics/src/lib.rs, smaller-challenges/egonomics/test.md, smaller-challenges/egonomics/tests/lib.rs, smaller-challenges/egonomics/withdraw.rtm
Submission from Scrypto Developer Event Budapest
=> egonomics token sale

smaller-challenges/tmp/Cargo.toml, smaller-challenges/tmp/src/lib.rs, smaller-challenges/tmp/src/transaction_manifest, smaller-challenges/tmp/tests/lib.rs
Hey there! Here is my solution. Cheers
=> Solve event challenge

lisbon/Cargo.toml, lisbon/src/lib.rs, lisbon/tests/lib.rs
=> scrypto-lisbon-challenge

smaller-challenges/iamashwin99/Cargo.toml, smaller-challenges/iamashwin99/src/lib.rs, smaller-challenges/iamashwin99/tests/lib.rs
=> Scrypto webinar challenge 

smaller-challenges/guildxyz/Cargo.toml, smaller-challenges/guildxyz/src/change.rtm, smaller-challenges/guildxyz/src/lib.rs, smaller-challenges/guildxyz/src/withdraw.rtm, smaller-challenges/guildxyz/tests/lib.rs
=> Scrypto challenge

smaller-challenges/avp-eagle-token/Cargo.toml, smaller-challenges/avp-eagle-token/src/lib.rs, smaller-challenges/avp-eagle-token/tests/lib.rs, smaller-challenges/avp-eagle-token/tx.rtm
Scrypto Developer Event Challenge
=> Scrypto Developer Event Challenge

smaller-challenges/borotoken/Cargo.toml, smaller-challenges/borotoken/src/lib.rs, smaller-challenges/borotoken/tests/lib.rs
=> borotoken again

smaller-challenges/gold-rush-sale/Cargo.toml, smaller-challenges/gold-rush-sale/src/lib.rs, smaller-challenges/gold-rush-sale/tests/lib.rs
Participants:
- 4025384239
- 4015981649
- 4054925729
- 4075211669
- 4024184869
=> Scrypto Challenge - Add gold rush token sale

4-portfolio-management-yield-farming/RadHedge/Cargo.toml, 4-portfolio-management-yield-farming/RadHedge/README.md, 4-portfolio-management-yield-farming/RadHedge/show_case.sh, 4-portfolio-management-yield-farming/RadHedge/src/investment_pool.rs, 4-portfolio-management-yield-farming/RadHedge/src/lib.rs, 4-portfolio-management-yield-farming/RadHedge/src/test_environment.rs, 4-portfolio-management-yield-farming/RadHedge/test_transactions/create_investment_pool.rtm, 4-portfolio-management-yield-farming/RadHedge/test_transactions/create_test_environment.rtm, 4-portfolio-management-yield-farming/RadHedge/test_transactions/fund_pool.rtm, 4-portfolio-management-yield-farming/RadHedge/tests/lib.rs
A decentralized asset management plattform.
Unfortunately I ran out of time for proper documentation and most importantly testing... 
Was a lot of fun though.
=> The RadHedge

4-portfolio-management-yield-farming/vaultz2/Cargo.toml, 4-portfolio-management-yield-farming/vaultz2/src/lib.rs, 4-portfolio-management-yield-farming/vaultz2/tests/lib.rs
submitting progress so far on Vaultz
=> adding vaultz

smaller-challenges/my_pi_slice_token_sale/Cargo.toml, smaller-challenges/my_pi_slice_token_sale/src/lib.rs, smaller-challenges/my_pi_slice_token_sale/tests/lib.rs
Here's my entrance for the challenge from the webinar last week.
=> my_pi_slice token sale challenge

smaller-challenges/pecilambo/Cargo.toml, smaller-challenges/pecilambo/src/lib.rs, smaller-challenges/pecilambo/tests/lib.rs
From Paulo, Cristiano, Ivo and Emanuel.
=> Submission from PECILAMBO team

smaller-challenges/myTeamMates/Cargo.toml, smaller-challenges/myTeamMates/src/lib.rs, smaller-challenges/myTeamMates/tests/lib.rs
=> myTeamates challange complete

7-defi-devpost/scrypto-lend-marketplace/README.md, 7-defi-devpost/scrypto-lend-marketplace/package-lock.json, 7-defi-devpost/scrypto-lend-marketplace/package.json, 7-defi-devpost/scrypto-lend-marketplace/public/index.html, 7-defi-devpost/scrypto-lend-marketplace/public/style.css, 7-defi-devpost/scrypto-lend-marketplace/scrypto/.gitignore, 7-defi-devpost/scrypto-lend-marketplace/scrypto/Cargo.toml, 7-defi-devpost/scrypto-lend-marketplace/scrypto/src/lib.rs, 7-defi-devpost/scrypto-lend-marketplace/snowpack.config.mjs, 7-defi-devpost/scrypto-lend-marketplace/src/index.js, 7-defi-devpost/scrypto-lend-marketplace/tailwind.config.js
Github repo - https://github.com/jayshreeanand/scrypto-lend-marketplace
=> PeerLend - scrypto lending marketplace
